# Generated by Django 5.1.4 on 2025-01-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_labo_langue_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100, verbose_name='Nom et Prénom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/photos/', verbose_name='Photo')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
    ]
