# Generated by Django 5.1.4 on 2025-01-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(blank=True, choices=[('Menu_home', 'Menu_home'), ('Populaire', 'Populaire'), ('Politique', 'Politique'), ('Societe', 'Societe'), ('Culture', 'Culture'), ('Sport', 'Sport'), ('Economie', 'Economie'), ('Sante', 'Sante'), ('Education', 'Education'), ('Divertissement', 'Divertissement')], max_length=20, null=True),
        ),
    ]
