# Generated by Django 5.1.4 on 2025-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_sous_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, default='Mechack', max_length=200),
        ),
    ]
