# Generated by Django 5.1.4 on 2025-01-14 13:40

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=200)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
