# Generated by Django 5.1.4 on 2025-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, default='Bénin Exellence', max_length=200),
        ),
    ]
